all: Ex04.out Ex05.out Ex06.out Ex07.out Ex08.out Ex09.out Ex10.out Ex11.out Ex12.out
Ex04.out: Ex04.c
	gcc Ex04.c -o Ex04.out
Ex05.out: Ex05.c
	gcc Ex05.c -o Ex05.out
Ex06.out: Ex06.c
	gcc Ex06.c -o Ex06.out
Ex07.out: Ex07.c
	gcc Ex07.c -o Ex07.out
Ex08.out: Ex08.c
	gcc Ex08.c -o Ex08.out
Ex09.out: Ex09.c
	gcc Ex09.c -o Ex09.out
Ex10.out: Ex10.c
	gcc Ex10.c -o Ex10.out
Ex11.out: Ex11.c
	gcc Ex11.c -o Ex11.out
Ex12.out: Ex12.c
	gcc Ex12.c -o Ex12.out -lpthread
clean:
	rm -f *.out *.bin *.txt