all: Ex01.out Ex02.out Ex03.out Ex04.out Ex05.out Ex06.out Ex07.out
Ex01.out: Ex01.c
	gcc Ex01.c -o busca_e_conta1.out
Ex02.out: Ex02.c
	gcc Ex02.c -o busca_e_conta2.out
Ex03.out: Ex03.c
	gcc Ex03.c -o Ex03.out
Ex04.out: Ex04.c
	gcc Ex04.c -o Ex04.out
Ex05.out: Ex05.c
	gcc Ex05.c -o Ex05.out
Ex06.out: Ex06.c
	gcc Ex06.c -o Ex06.out
Ex07.out: Ex07.c
	gcc Ex07.c -o Ex07.out
clean:
	rm -f *.out *.bin *.txt