all: Ex1.out Ex2.out Ex3.out Ex4.out Ex5.out Ex6.out Ex7.out Ex8.out eatmem.out
Ex1.out: Ex1.c
	gcc Ex1.c -o Ex1.out
Ex2.out: Ex2.c
	gcc Ex2.c -o Ex2.out
Ex3.out: Ex3.c
	gcc Ex3.c -o Ex3.out
Ex4.out: Ex4.c
	gcc Ex4.c -o Ex4.out
Ex5.out: Ex5.c
	gcc Ex5.c -o Ex5.out
Ex6.out: Ex6.c
	gcc Ex6.c -o Ex6.out
Ex7.out: Ex7.c
	gcc Ex7.c -o Ex7.out
Ex8.out: Ex8.c
	gcc Ex8.c -o Ex8.out
eatmem.out: eatmem.c
	gcc eatmem.c -o eatmem.out
clock_times.out: clock_times.c
	gcc clock_times.c -o clock_times.out
clean:
	rm -f *.out *.bin *.txt

