all: Ex01.out Ex02.out Ex03.out Ex04.out Ex05.out Ex06.out Ex07.out Ex08.out Ex09.out Ex10.out Ex11.out
Ex01.out: Ex01.c
	gcc Ex01.c -o busca_e_conta1.out
Ex02.out: Ex02.c
	gcc Ex02.c -o busca_e_conta2.out
Ex03.out: Ex03.c
	gcc Ex03.c -o Ex03.out
Ex04.out: Ex04.c
	gcc Ex04.c -o Ex04.out
Ex05.out: Ex05.c
	gcc Ex05.c -o Ex05.out
Ex06.out: Ex06.c
	gcc Ex06.c -o Ex06.out
Ex07.out: Ex07.c
	gcc Ex07.c -o Ex07.out
Ex08.out: Ex08.c
	gcc Ex08.c -o Ex08.out -lpthread
Ex09.out: Ex09.c
	gcc Ex09.c -o Ex09.out -lpthread
Ex10.out: Ex10.c
	gcc Ex10.c -o Ex10.out
Ex11.out: Ex11.c
	gcc Ex11.c -o Ex11.out
clean:
	rm -f *.out *.bin *.txt