all: Ex1.out Ex2.out teste_retorno Ex3.out Ex4.out Ex5.out Ex6.out Ex7.out Ex8.out Ex9.out
Ex1.out: Ex1.c
	gcc Ex1.c -o Ex1.out
Ex2.out: Ex2.c
	gcc Ex2.c -o Ex2.out
teste_retorno: Ex3a.c
	gcc Ex3a.c -o teste_retorno
Ex3.out: Ex3b.c
	gcc Ex3b.c -o Ex3.out
Ex4.out: Ex4.c
	gcc Ex4.c -o Ex4.out
Ex5.out: Ex5.c
	gcc Ex5.c -o Ex5.out
Ex6.out: Ex6.c
	gcc Ex6.c -o Ex6.out
Ex7.out: Ex7.c
	gcc Ex7.c -o Ex7.out
Ex8.out: Ex8.c
	gcc Ex8.c -o Ex8.out
Ex9.out: Ex9.c
	gcc Ex9.c -o Ex9.out
clean:
	rm -f *.out *.bin *.txt teste_retorno