all:
	gcc Q01_linux.c -o Qc01
	gcc Q02_linux.c -o Qc02
	gcc Q03_linux.c -o Qc03
	gcc Q04_linux.c -o Qc04
	gcc Q05_linux.c -o Qc05
	gcc Q06_linux.c -o Qc06
	gcc Q07_linux.c -o Qc07
	gcc Q08_linux.c -o Qc08
	gcc Q09_linux.c -o Qc09
	gcc Q10_linux.c -o Qc10 -lpthread
	gcc Q11_linux.c -o Qc11 -lpthread
	gcc Q12_linux.c -o Qc12
	gcc Q13_linux.c -o Qc13
clean:
	rm -f Qc*
