all:
	gcc Q1_linux.c -o Qc1
	gcc Q2_linux.c -o Qc2
	gcc Q3_linux.c -o Qc3
	gcc Q4_linux.c -o Qc4
	gcc Q5_linux.c -o Qc5
	gcc Q6_linux.c -o Qc6
	gcc Q7_linux.c -o Qc7
	gcc Q8_linux.c -o Qc8
	gcc Q9_linux.c -o Qc9
	gcc Q10_linux.c -o Qc10 -lpthread
	gcc Q11_linux.c -o Qc11 -lpthread
clean:
	rm -f Qc*
