all: Ex01.out Ex02.out Ex03.out Ex04.out Ex05.out Ex06.out Ex07.out Ex08.out Ex09.out Ex10.out Ex11.out Ex12.out Ex13.out Ex14.out Ex15.out Ex16.out Ex17.out Ex18.out Ex19.out Ex20.out Ex21.out Ex22.out
Ex01.out: Ex01.c
	gcc Ex01.c -o Ex01.out `pkg-config --cflags --libs gtk+-2.0`
Ex02.out: Ex02.c
	gcc Ex02.c -o Ex02.out `pkg-config --cflags --libs gtk+-2.0`
Ex03.out: Ex03.c
	gcc Ex03.c -o Ex03.out `pkg-config --cflags --libs gtk+-2.0`
Ex04.out: Ex04.c
	gcc Ex04.c -o Ex04.out `pkg-config --cflags --libs gtk+-2.0`
Ex05.out: Ex05.c
	gcc Ex05.c -o Ex05.out `pkg-config --cflags --libs gtk+-2.0`
Ex06.out: Ex06.c
	gcc Ex06.c -o Ex06.out `pkg-config --cflags --libs gtk+-2.0`
Ex07.out: Ex07.c
	gcc Ex07.c -o Ex07.out `pkg-config --cflags --libs gtk+-2.0`
Ex08.out: Ex08.c
	gcc Ex08.c -o Ex08.out `pkg-config --cflags --libs gtk+-2.0`
Ex09.out: Ex09.c
	gcc Ex09.c -o Ex09.out `pkg-config --cflags --libs gtk+-2.0`
Ex10.out: Ex10.c
	gcc Ex10.c -o Ex10.out `pkg-config --cflags --libs gtk+-2.0`
Ex11.out: Ex11.c
	gcc Ex11.c -o Ex11.out `pkg-config --cflags --libs gtk+-2.0`
Ex12.out: Ex12.c
	gcc Ex12.c -o Ex12.out `pkg-config --cflags --libs gtk+-2.0`
Ex13.out: Ex13.c
	gcc Ex13.c -o Ex13.out `pkg-config --cflags --libs gtk+-2.0`
Ex14.out: Ex14.c
	gcc Ex14.c -o Ex14.out `pkg-config --cflags --libs gtk+-2.0`
Ex15.out: Ex15.c
	gcc Ex15.c -o Ex15.out `pkg-config --cflags --libs gtk+-2.0`
Ex16.out: Ex16.c
	gcc Ex16.c -o Ex16.out `pkg-config --cflags --libs gtk+-2.0`
Ex17.out: Ex17.c
	gcc Ex17.c -o Ex17.out `pkg-config --cflags --libs gtk+-2.0`
Ex18.out: Ex18.c
	gcc Ex18.c -o Ex18.out `pkg-config --cflags --libs gtk+-2.0`
Ex19.out: Ex19.c
	gcc Ex19.c -o Ex19.out `pkg-config --cflags --libs gtk+-2.0`
Ex20.out: Ex20.c
	gcc Ex20.c -o Ex20.out `pkg-config --cflags --libs gtk+-2.0`
Ex21.out: Ex21.c
	gcc Ex21.c -o Ex21.out `pkg-config --cflags --libs gtk+-2.0`
Ex22.out: Ex22.c
	gcc Ex22.c -o Ex22.out `pkg-config --cflags --libs gtk+-2.0`
clean:
	rm -f *.out *.bin *.txt
